## 1.Split this String

In [1]:
s="Hi there sam!"
v=s.split()
print(v)

['Hi', 'there', 'sam!']


## 2.Use .format()to print the following String

In [5]:
plant ="Earth"
diameter ="12742"
v="The diameter of Earth is {an} kilometer"
print(v.format(an=12742))

The diameter of Earth is 12742 kilometer


## 3.In this nest dictionary grab the word "hello

In [1]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(d['k1'][3]["tricky"][3]['target'][3])

hello


## 5.Create an array of all the even integers from 20 to 35

In [10]:
import numpy as np
array=np.arange(20,35,2)
print("Array =",array)

Array = [20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with value ranging from 0 to 8

In [17]:
import numpy as np
x =  np.arange(0, 9)
print(x.reshape(3,3))


[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate a and b 

In [6]:
import numpy as np

a = np.array([1, 2, 3])

b = np.array([4, 5, 6])

v = np.concatenate((a, b))

print(v)

[1 2 3 4 5 6]


## 8.Create a dataframe with 3 rows and 2 columns

In [17]:
import pandas as pd

data = {
  "x": [1,2,3],
  "y": [4,5,6]
}
df = pd.DataFrame(data)

print(df) 

   x  y
0  1  4
1  2  5
2  3  6


## 9.Generate the series of dates from 1st Jan,2023 to 10th Feb 2023

In [11]:
import pandas as pd
a= pd.date_range(start='2023-01-01', end='2023-02-10')
print(a)

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10', '2023-01-11', '2023-01-12',
               '2023-01-13', '2023-01-14', '2023-01-15', '2023-01-16',
               '2023-01-17', '2023-01-18', '2023-01-19', '2023-01-20',
               '2023-01-21', '2023-01-22', '2023-01-23', '2023-01-24',
               '2023-01-25', '2023-01-26', '2023-01-27', '2023-01-28',
               '2023-01-29', '2023-01-30', '2023-01-31', '2023-02-01',
               '2023-02-02', '2023-02-03', '2023-02-04', '2023-02-05',
               '2023-02-06', '2023-02-07', '2023-02-08', '2023-02-09',
               '2023-02-10'],
              dtype='datetime64[ns]', freq='D')


## 10.Create 2D list to data frame

In [8]:
import pandas as pd
import numpy as np
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
v=pd.DataFrame(lists)
print(v)

   0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24
